'use strict'

const USER_HEADER = "LOG_U_T_" ;

const CACHE_APPEND_PSWD = "PWD_";
const CACHE_APPEND_SIGN = "SIGN_";

const EXPIRED_TIME_PSWD_SMS = 900;

module.exports = { USER_HEADER ,CACHE_APPEND_PSWD , CACHE_APPEND_SIGN, EXPIRED_TIME_PSWD_SMS}